[package]
name = "cryptopals_rs"
version = "0.1.0"
authors = ["toidiu <apoorv@toidiu.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13"
hex = "0.4"
bytes = "^1.0"
